### ISSUE TITLE
unable to test changes locally

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#544]
### What is the issue?

- After pushing new change we need to wait for long time to test our changes in the pipeline.
- Some time pipeline fails due to some other reasons in infra setup stage only and because of that also we cant test our change. We need to wait until the fix is done.

**Comment by AmitKumarDas** [comment]
One of the items that I am doing is by implementing a simple custom resource that is native to kubernetes, can be tested on one's laptop, should run faster since it does not resort to cli commands _(read kubectl, jq, sed, awk, bash, etc)_ to test & assert. This is implemented as part of https://github.com/mayadata-io/oep-e2e/issues/537.

**Comment by AmitKumarDas** [comment]
This is being worked upon as part of d-operators' controllers
