### ISSUE TITLE
Gui test cases are failing in Konvoy pipeline

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#761]
- GUI test cases are failing in Konvoy pipeline
    - `TCID-GUI-AUTH` (regression)
    - `TCID-GUI-CLUSTER`(flaky)
    - `TCID-DIR-DMAAS-SCHD-CSTOR-MINIO-BUCKET`
    - `TCID-DIR-DMAAS-SCHD-JIVA-MINIO-BUCKET`

**Comment by rohan2794** [comment]
TCID-GUI-AUTH failing due to product issue: https://github.com/mayadata-io/oep/issues/118
TCID-GUI-CLUSTER , minor fix needed in selenium code
TCID-DIR-DMAAS-SCHD-CSTOR-MINIO-BUCKET: Restore is failing on cluster 3 due mount volume error.
TCID-DIR-DMAAS-SCHD-JIVA-MINIO-BUCKET: taking more time to generate backup , selenium code need to be refactored.

**Comment by rohan2794** [comment]
ref: https://github.com/mayadata-io/gui-automation/pull/43

**Comment by rohan2794** [comment]
ref: https://github.com/mayadata-io/oep/issues/166
