### ISSUE TITLE
Gitlab certificate issue

### ISSUE THREAD

**Issue by prabhatkumarthakur** [mayadata-io/oep-e2e#805]
Due to Gitlab certificate issue, we are not able to trigger pipline and other GitLab functionality cannot be used.

**Comment by prabhatkumarthakur** [comment]
![image](https://user-images.githubusercontent.com/20839334/87351623-510fee00-c577-11ea-8eac-91700092032a.png)

**Comment by prabhatkumarthakur** [comment]
Gitlab certificate got expired on 12 July 2020
![image](https://user-images.githubusercontent.com/20839334/87351783-90d6d580-c577-11ea-82b1-688506890a2d.png)

**Comment by harshshekhar15** [comment]
# Issue
SSL certificate for Gitlab was expired and it was not getting renewed. The issue was due to improper installation of Gitlab on AWS while migration from GKE. On AWS, a load balancer is being used to forward the request from outside the cluster to the ingress. As expected, the request was getting forwarded to port 443 due to which the `gitlab-cert-manager` was not able to renew the certificates as it was expecting the request on port 80 and port 80 was not open for the requests from outside.

# Fix
To fix the above issue the following steps were performed:
- Enable port 80 in the firewall for all traffic.
- Delete the secret which has the older ssl certificates.
- Restart the `gitlab-cert-manager` pod.
